- name: configure frontend server
  hosts: frontend
  become: yes

  tasks:
  - name: disable default nginx version
    ansible.builtin.command: dnf module disable nginx -y
    
  - name: enable nginx 1.24 which is recommended by dev team
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove default html directory
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/

  - name: create html directory
    ansible.builtin.file:
      state: directory
      path: /usr/share/nginx/html/

  - name:

  